services:
  _defaults:
    autowire: true
    autoconfigure: true
    tags:
      - { name: lumina.schema_sdl }
      - { name: lumina.directive }
    bind:
      $userColumn: '%lumina.user_column%'

  # Automatically register all directive definitions
  Netmex\Lumina\Directives\Definition\:
    resource: '../src/Directives/Definition/*'
